image: s2shape/s2shape-test-harness:latest

stages:
  - build
  - test

variables:
  KUDU_HOST: kudu
  KUDU_PORT: "7051"
  KUDU_MASTER_EXTRA_OPTS: "--block_manager=file --webserver_advertised_addresses kudu:8051 --rpc_advertised_addresses kudu:7051"
  KUDU_TSERVER_EXTRA_OPTS: "--block_manager=file --webserver_advertised_addresses kudu:8050 --rpc_advertised_addresses kudu:7050"
  COMPlus_DebugWriteToStdErr: "1"

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  services:
    - name: s2shape/kudu-dev
      alias: kudu
      entrypoint: ["/bin/sh","-c" ,'echo "127.0.0.1 kudu">>/etc/hosts && /entrypoint']

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/KuduSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init KuduSupplyCollector kudu://$KUDU_HOST:$KUDU_PORT
    - dotnet SupplyCollectorDataLoader.dll -xunit KuduSupplyCollector kudu://$KUDU_HOST:$KUDU_PORT
    - cd $ROOT_PROJECT_PATH
    - dotnet test

load_test:
  stage: test
  services:
    - name: s2shape/kudu-dev
      alias: kudu
      entrypoint: ["/bin/sh","-c" ,'echo "127.0.0.1 kudu">>/etc/hosts && /entrypoint']

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/KuduSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init KuduSupplyCollector kudu://$KUDU_HOST:$KUDU_PORT
    - dotnet SupplyCollectorDataLoader.dll -xunit KuduSupplyCollector kudu://$KUDU_HOST:$KUDU_PORT
    - dotnet SupplyCollectorDataLoader.dll -samples KuduSupplyCollector kudu://$KUDU_HOST:$KUDU_PORT TestCollection Test1:int,Test2:string,Test3:bool,Test4:double,Test5 1000000
    - cd $ROOT_PROJECT_PATH/KuduSupplyCollectorTests/bin/Debug/netcoreapp2.2/publish
    - SupplyCollectorTestHarness
